# yamllint disable rule:document-start
# yamllint disable rule:line-length

icloud3_action:
  description: This service allows you to change the way iCloud3 operates.
  fields:
    device_name:
      description: Name of the device to be updated. All devices will be updated if this parameter is not specified. (Optional)
      example: gary_iphone
    command:
      description: The action to be performed. (Required)
      example: log_level debug

icloud3_update:
  description: This service allows you to change the way iCloud3 operates.
  fields:
    device_name:
      description: Name of the device to be updated. All devices will be updated if this parameter is not specified. (Optional)
      example: gary_iphone
    command:
      description: The action to be performed. (Required)
      example: log_level debug

icloud3_restart:
  description: This service will refresh all of the devices being handled by iCloud3 and can be used when you have added a new device to your Apple account. You will have to restart Home Assist if you have made changes to the platform parameters (new device type, new device name, etc.)
  fields:
    account_name:
      description: account_name of the iCloud3 custom component specified in the Configuration Variables section described at the beginning of this document. (Required)
      example: gary_icloud

icloud3_lost_iphone:
  description: This service will play the Lost iPhone sound on a specific device.
  fields:
    device_name:
      description: Name of the device to be located (required).
      example: gary_icloud

icloud3_find_phone_alert:
  description: This service will send a find phone message to the specific device.
  fields:
    device_name:
      description: Name of the device to be located (required).
      example: gary_icloud
