#####
# Default Config
# https://www.home-assistant.io/integrations/default_config/
#
# This integration is a meta-component and configures a default set of integrations for Home Assistant to load.
#####

default_config:
