id: 4b293604-06a6-11ee-be56-0242ac120002
alias: Turn on TV lights when TV is playing
description: ''

trigger:
- platform: state
  entity_id:
  - media_player.living_room_apple_tv
  - media_player.living_room_tv
  to: playing
  for:
    hours: 0
    minutes: 0
    seconds: 5

condition: []

action:
- service: light.turn_on
  data: {}
  target:
    entity_id: light.living_room_tv_lights

mode: single
